# fuzzel — 应用启动器（Mod+D）
font=Noto Sans CJK SC:size=11
terminal=foot
dpi-aware=no
icon-theme=Adwaita
width=60

[colors]
background=242428f2
text=ffffffff
match=99c8ffff
selection=3a3a41ff
selection-text=ffffffff
border=4d4d55ff

[border]
width=2
radius=10
